---
# tasks file for ansible-role-horizon-view-agent

- name: Check if Horizon View Agent is already installed
  stat:
    path: /usr/lib/vmware/viewagent/bin/StartAgent.sh
  register: view_agent_already_installed

- name: Copy over Horizon View Agent tarball
  ansible.builtin.copy:
    src: VMware-horizonagent-linux-x86_64-7.13.0-16944161.tar.gz
    dest: /tmp/VMware-horizonagent-linux-x86_64-7.13.0-16944161.tar.gz
    owner: root
    group: root
    mode: '0644'
  when: view_agent_already_installed.stat.exists == 0

- name: Extract Horizon View Agent tarball
  ansible.builtin.unarchive:
    src: /tmp/VMware-horizonagent-linux-x86_64-7.13.0-16944161.tar.gz
    dest: /tmp
    remote_src: yes
  when: view_agent_already_installed.stat.exists == 0

- name: Install Horizon View Agent
  ansible.builtin.shell: ./install_viewagent.sh -A yes -a yes -f yes -F no -S no -U no -C no
  args:
    chdir: /tmp/VMware-horizonagent-linux-x86_64-7.13.0-16944161
  when: view_agent_already_installed.stat.exists == 0

- name: Remove Horizon View Agent tarball
  ansible.builtin.file:
    path: /tmp/VMware-horizonagent-linux-x86_64-7.13.0-16944161.tar.gz
    state: absent
  when: view_agent_already_installed.stat.exists == 0

- name: Recursively remove Horizon View Agent tarball extracted directory
  ansible.builtin.file:
    path: /tmp/VMware-horizonagent-linux-x86_64-7.13.0-16944161
    state: absent
  when: view_agent_already_installed.stat.exists == 0
